# fly.toml app configuration file generated for fudisc-web-nextjs on 2023-10-23T18:25:27+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "fudisc-web-nextjs"
primary_region = "arn"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
